project:
  type: website
  output-dir: docs
  preview:
    browser: true
  render:
    - "*.qmd"
  resources:
    - "content/"
    - "css/"
    - "static/"
    - "images/"

website:
  title: "Diellza Muriqi"
  description: "The personal website of Diellza Muriqi"
  image: images/photo.jpeg
  site-url: https://diellzamuriqi.github.io
  repo-url: https://github.com/diellzamuriqi/diellzamuriqi.github.io

  search:
    location: navbar
    type: overlay

  back-to-top-navigation: false

  open-graph:
    site-name: "Diellza Muriqi"

  navbar:
    right:
      - text: "About"
        href: bio.qmd
      - text: "Research"
        href: research.qmd
      - text: "Teaching"
        href: teaching.qmd
      - text: "CV"
        href: cv.qmd

  page-footer:
    center:
      - text: |
          <a href='cv.html'>CV</a>
          &nbsp;
          <a href='https://github.com/diellzamuriqi' target='_blank'><i class='bi bi-github'></i></a>
          &nbsp;
          <a href='https://www.linkedin.com/in/diellzamuriqi/' target='_blank'><i class='bi bi-linkedin'></i></a>
          &nbsp;
          <a href='https://scholar.google.com/citations?user=1WwDhp0AAAAJ&hl=en' target='_blank'><i class='ai ai-google-scholar fa-lg'></i></a>
          &nbsp;
          <a href='https://orcid.org/0009-0004-1863-0315' target='_blank'><i class='ai ai-orcid fa-lg'></i></a>
          <br>
          Site made with <a href='https://quarto.org/' target='_blank'>Quarto</a>
          <br>
          © 2026 Diellza Muriqi

format:
  html:
    theme: [default, css/theme.scss]
    anchor-sections: true
    smooth-scroll: true
    link-external-newwindow: true
    link-external-icon: false
    include-in-header: "_includes/header.html"